#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : popt
Version  : 1.18
Release  : 24
URL      : file:///aot/build/clearlinux/packages/popt/popt-v1.18.tar.gz
Source0  : file:///aot/build/clearlinux/packages/popt/popt-v1.18.tar.gz
Summary  : popt library.
Group    : Development/Tools
License  : MIT
Requires: popt-lib = %{version}-%{release}
Requires: popt-locales = %{version}-%{release}
Requires: popt-man = %{version}-%{release}
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gettext
BuildRequires : glibc-dev
BuildRequires : glibc-staticdev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libstdc++
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : ncurses-dev
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the popt(3) command line option parsing library. While it is similar
to getopt(3), it contains a number of enhancements, including:

%package dev
Summary: dev components for the popt package.
Group: Development
Requires: popt-lib = %{version}-%{release}
Provides: popt-devel = %{version}-%{release}
Requires: popt = %{version}-%{release}

%description dev
dev components for the popt package.


%package lib
Summary: lib components for the popt package.
Group: Libraries

%description lib
lib components for the popt package.


%package locales
Summary: locales components for the popt package.
Group: Default

%description locales
locales components for the popt package.


%package man
Summary: man components for the popt package.
Group: Default

%description man
man components for the popt package.


%package staticdev
Summary: staticdev components for the popt package.
Group: Default
Requires: popt-dev = %{version}-%{release}

%description staticdev
staticdev components for the popt package.


%prep
%setup -q -n popt
cd %{_builddir}/popt

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622020704
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g3 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -fno-plt -mtls-dialect=gnu2 -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -pthread -static-libstdc++ -static-libgcc"
export FCFLAGS="-g3 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -fno-plt -mtls-dialect=gnu2 -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -pthread -static-libstdc++ -static-libgcc"
export FFLAGS="-g3 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -fno-plt -mtls-dialect=gnu2 -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -pthread -static-libstdc++ -static-libgcc"
export CXXFLAGS="-g3 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -fno-plt -mtls-dialect=gnu2 -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -pthread -static-libstdc++ -static-libgcc"
export LDFLAGS="-g3 -O2 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -fno-plt -mtls-dialect=gnu2 -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -pthread -static-libstdc++ -static-libgcc -lpthread"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags1 end
sd -r '\s--dirty\s' ' ' .
sd -r 'git describe' 'git describe --abbrev=0' .
sd --flags mi '^AC_INIT\((.*\n.*\)|.*\))' '$0\nAM_MAINTAINER_MODE([disable])' configure.ac
%autogen --enable-static --enable-shared
make  %{?_smp_mflags}  V=1 VERBOSE=1  V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1622020704
rm -rf %{buildroot}
%make_install
%find_lang popt

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/popt.h
/usr/lib64/libpopt.so
/usr/lib64/pkgconfig/popt.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpopt.so.0
/usr/lib64/libpopt.so.0.0.1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man3/popt.3

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libpopt.a

%files locales -f popt.lang
%defattr(-,root,root,-)
